production:
  adapter: postgresql
  encoding: unicode
  database: dokumendid
  pool: 5
  username: Jnx
  password: JnxVale

development:
  adapter: postgresql
  encoding: unicode
  database: dokumendid_dev
  host: localhost
  pool: 5
  username: Jnx
  password: Jnx

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
